# Generated by Django 4.1.6 on 2023-03-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_alter_userimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
