# Generated by Django 4.1.6 on 2023-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0006_question_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug_title',
            field=models.SlugField(blank=True, max_length=600, null=True),
        ),
    ]
