# Generated by Django 4.1.6 on 2023-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0008_alter_userimage_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
